baseURL = 'https://precept.sh/'
languageCode = 'en-us'
title = 'Precept'
description = 'Precept is an api integration platform'

# Language settings
contentDir = 'content/en'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = false

enableRobotsTXT = true

enableEmoji = true

[services]

[services.googleAnalytics]
id = 'G-HXR4W4V64Z'

[module]
proxy = "direct"

[module.hugoVersion]
min = "0.123.0"
extended = true

[[module.imports]]
path = "github.com/google/docsy"

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser.attribute]
block = true # default is false

[params]

[params.ui]
footer_about_enable = true

[params.copyright]
authors = "Precept, LLC"
from_year = 2024

[params.links]

[[params.links.developer]]
name = 'Proof Partners, LLC'
url = 'https://proofpartners.io'
